import { Lato } from 'next/font/google';
import MainNavigation from '@/components/MainNavigation/MainNavigation';
import AuthProvider from './auth/Provider';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import './globals.css';

const lato = Lato({ subsets: ['latin'], weight: ['400', '700', '900'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={lato.className}>
        <AuthProvider>
          <ToastContainer />
          <MainNavigation />
          <main>{children}</main>
        </AuthProvider>
      </body>
    </html>
  );
}
